from __future__ import annotations

import html
import json
from typing import Any, Iterable, List


def format_params(value: float) -> str:
    value = float(value or 0)
    units = [(1e12, "T"), (1e9, "B"), (1e6, "M"), (1e3, "K")]
    for scale, suffix in units:
        if abs(value) >= scale:
            return f"{value / scale:.2f}{suffix}"
    return str(int(value))


def format_bytes(value: float) -> str:
    value = float(value or 0)
    units = [
        (1024**4, "TiB"),
        (1024**3, "GiB"),
        (1024**2, "MiB"),
        (1024, "KiB"),
    ]
    for scale, suffix in units:
        if abs(value) >= scale:
            return f"{value / scale:.2f} {suffix}"
    return f"{int(value)} B"


def pct_delta(left: float, right: float) -> str:
    if left == 0 and right == 0:
        return "0%"
    if left == 0:
        return "new"
    return f"{(right - left) / left * 100:+.1f}%"


def shape_text(shape: Iterable[int]) -> str:
    values = list(shape)
    if not values:
        return "?"
    return "[" + ",".join(str(v) for v in values) + "]"


def json_dumps(data: Any) -> str:
    return json.dumps(data, indent=2, ensure_ascii=False, sort_keys=True)


def markdown_table(headers: List[str], rows: List[List[str]]) -> str:
    if not rows:
        return ""
    escaped_rows = [[str(cell).replace("\n", "<br/>") for cell in row] for row in rows]
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    lines.extend("| " + " | ".join(row) + " |" for row in escaped_rows)
    return "\n".join(lines)


def html_page(title: str, body: str) -> str:
    escaped = html.escape(body)
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{html.escape(title)}</title>
  <style>
    :root {{
      color-scheme: light dark;
      --bg: #f6f7f9;
      --fg: #17202a;
      --muted: #596574;
      --panel: #ffffff;
      --line: #d8dde6;
      --accent: #0f766e;
    }}
    @media (prefers-color-scheme: dark) {{
      :root {{
        --bg: #101418;
        --fg: #e7ebef;
        --muted: #aab4bf;
        --panel: #171c22;
        --line: #2d3540;
        --accent: #2dd4bf;
      }}
    }}
    body {{
      margin: 0;
      background: var(--bg);
      color: var(--fg);
      font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }}
    main {{
      max-width: 1180px;
      margin: 0 auto;
      padding: 28px 20px 48px;
    }}
    h1 {{
      margin: 0 0 16px;
      font-size: 24px;
      letter-spacing: 0;
    }}
    pre {{
      overflow: auto;
      border: 1px solid var(--line);
      background: var(--panel);
      border-radius: 8px;
      padding: 18px;
      line-height: 1.45;
      font-size: 13px;
      white-space: pre-wrap;
    }}
    .meta {{
      color: var(--muted);
      margin-bottom: 18px;
    }}
    .accent {{
      color: var(--accent);
    }}
  </style>
</head>
<body>
  <main>
    <h1>{html.escape(title)}</h1>
    <div class="meta">Generated by <span class="accent">mad</span></div>
    <pre>{escaped}</pre>
  </main>
</body>
</html>
"""
